// <auto-generated />
using System;
using Hotel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190521211540_AddFildSuppy")]
    partial class AddFildSuppy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hotel.Models.CheckIn", b =>
                {
                    b.Property<int>("CheckInID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Arrival");

                    b.Property<int>("CustomerID");

                    b.Property<DateTime>("Department");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("RoomID");

                    b.HasKey("CheckInID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("RoomID");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("Hotel.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BithDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Hotel.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Comments");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<bool>("State");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Comments");

                    b.Property<decimal>("Price");

                    b.Property<string>("ServiceName")
                        .IsRequired();

                    b.Property<bool>("State");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Hotel.Models.Supply", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CheckInID");

                    b.Property<int>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("ServiceID");

                    b.Property<string>("ServiceName")
                        .IsRequired();

                    b.Property<DateTime>("SupplyDate");

                    b.HasKey("SupplyID");

                    b.HasIndex("CheckInID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Supplys");
                });

            modelBuilder.Entity("Hotel.Models.CheckIn", b =>
                {
                    b.HasOne("Hotel.Models.Customer", "CustomerIDNavigation")
                        .WithMany("CheckInsCustomerIDNavigation")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel.Models.Room", "RoomIDNavigation")
                        .WithMany("CheckInsRoomIDNavigation")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Models.Supply", b =>
                {
                    b.HasOne("Hotel.Models.CheckIn", "CheckInIDNavigation")
                        .WithMany("SupplysCheckInIDNavigation")
                        .HasForeignKey("CheckInID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel.Models.Service", "ServiceIDNavigation")
                        .WithMany("SupplysServiceIDNavigation")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
